version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./
    ports:
      - 3000:3000
      
  frontend:
    build:
      context: ./frontend
      dockerfile: ./
    ports:
      - 8080:80
