name: Build and Deploy

on:
    push:
        branches: 
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Frontend App
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend
                  push: true
                  tags: hasbii/resto-menu-fe:latest

            - name: Build and push Backend App
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  push: true
                  tags: hasbii/resto-menu-be:latest

    deploy:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: SSH & Docker Compose
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.PATH }} && docker compose down && docker compose up -d
